class WeightNet
  attr_accessor :net
  
  # Use a DAG generated by StructureLearning to create an unweighted Bayes net
  def initialize(dag)
    vars = {}
    @net = Sbn::Net.new(title)
    
    vertices.each do |v|
      vars[v] = Sbn::Variable.new(@net, v.name.to_sym)
    end
    
    edges.each do |e|
      vars[e.source].add_child(vars[e.target])
    end
  end
end